datasets: 
    wikitext103: en
    chinese_documents: zh

models:
    copyisallyouneed: 
        model_name: Copyisallyouneed
        dataset_name: CopyisallyouneedWikitext103Dataset
        # dataset_name: CopyisallyouneedChineseDataset

# ========= Global configuration ========== #
root_dir: /dockerdata/johntianlan/sources/Copyisallyouneed
data_root_dir: /dockerdata/johntianlan/sources/Copyisallyouneed/data/wikitext103_1024
version: 2000
# ========= Global configuration ========== #
